# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Computer science 
  de: Informatik 
  cz: Informatika 
email: dansmrcka@live.com 
index:
  en: index.html
  de: index-de.html
  cz: index-cz.html
feed:
  en: /feed-en.xml
  de: /feed-de.xml
  cz: /feed-cz.xml

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hucko-sro.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: DanSmrcka 

# slow reading speed for article reading time
words_per_minute: 100

# github on site
github:
  username: DanSmrcka 
  url: https://github.com/dansmrcka

# Build settings
markdown: kramdown

# Exclude for build
exclude: [.idea]

# post url
permalink: /:categories/:title:output_ext

# Grouped content
collections: 
  forwards:
    output: true

# Translations
description:
  en: An information source about studying computer science at Karlsruher Institute of Technology
  de: Eine Informationsquelle über das Informatikstudium am Karlsruher Institut für Technologie
  cz: CZ Eine Informationsquelle über das Informatikstudium am Karlsruher Institut für Technologie
more:
  en: Read more
  de: Mehr lesen
  cz: Ctete dale
overview:
  en: All posts
  de: Alle Artikel
  cz: Vsechny prispevky
contact:
  en: Contact us!
  de: Schreib uns!
  cz: Napiste nam!

t:
  en:
    latest-posts:  "Latest Posts"
    read-more:  "Read More →"
    show-more:  "Show More →"
    loading:  "Loading..."
    on-word: "on"
    contact: "Contact"
    contact-page: "contact.md"
    read-time: "min"
    comments: "comments"
    go-to-home-page: "Go to the Home Page"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"
    all-posts-category: "All posts in the category"
    privacy: "Privacy"
    privacy_url: "/privacy"

  de:
      latest-posts:  "Neuste Artikel"
      read-more:  "Weiterlesen →"
      show-more:  "Mehr →"
      loading:  "Lädt..."
      on-word: "on"
      contact: "Kontakt"
      contact-page: "contact.md"
      read-time: "min"
      comments: "comments"
      go-to-home-page: "Zurück zur Startseite"
      months:
        january: "Jan"
        february: "Feb"
        march: "Mär"
        april: "Apr"
        may: "Mai"
        june: "Jun"
        july: "Jul"
        august: "Aug"
        september: "Sep"
        october: "Okt"
        november: "Nov"
        december : "Dez"
      all-posts-category: "Alle Artikel der Kategorie"
      privacy: "Datenschutz"
      privacy_url: "/datenschutz"

  cz:
      latest-posts:  "Neuste Artikel"
      read-more:  "Weiterlesen →"
      show-more:  "Mehr →"
      loading:  "Lädt..."
      on-word: "on"
      contact: "Kontakt"
      contact-page: "contact.md"
      read-time: "min"
      comments: "comments"
      go-to-home-page: "Zurück zur Startseite"
      months:
        january: "Jan"
        february: "Feb"
        march: "Mär"
        april: "Apr"
        may: "Mai"
        june: "Jun"
        july: "Jul"
        august: "Aug"
        september: "Sep"
        october: "Okt"
        november: "Nov"
        december : "Dez"
      all-posts-category: "Alle Artikel der Kategorie"
      privacy: "Datenschutz"
      privacy_url: "/datenschutz"

