# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Computer science @KIT
  de: Informatik @KIT
email: info@cs-k.it
description:
  en: An information source about studying computer science at Karlsruher Institute of Technology
  de: Eine Informationsquelle über das Informatikstudium am Karlsruher Institut für Technologie
index:
  en: index.html
  de: uebersicht.html
feed:
  en: /feed.xml
  de: /feed_de.xml
baseurl: "/study-guide" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  cs-kit

# Build settings
markdown: kramdown
