# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Hucko s.r.o
  de: Hucko s.r.o.  
  cz: Hucko s.r.o.  
email: jan.hucko@seznam.cz
index:
  en: index-en.html
  de: index.html
  cz: index-cz.html
feed:
  en: /feed-en.xml
  de: /feed-de.xml
  cz: /feed-cz.xml

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hucko-sro.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: DanSmrcka 

# slow reading speed for article reading time
words_per_minute: 100

ICO: CZ08407401
address: Kraslice, Pod nemocnicí 107, 35801
phone: 00420721269706

# github on site
github:
  username: DanSmrcka 
  url: https://github.com/dansmrcka

# Build settings
markdown: kramdown

# Exclude for build
exclude: [.idea]

# post url
permalink: /:categories/:title:output_ext

# Grouped content
collections: 
  forwards:
    output: true

# Translations
description:
  en: Mediation of business, services and targeted search in the Czech and Slovak Republics 
  de: Geschäfte- und Dienstleistungenvermittlung sowie gezieltes Aussuchen in der Tschechischen und Slowakischen Republik  
  cz: Zprostředkování obchodu, služeb a cílené vyhledávání v České a Slovenské republice
more:
  en: Read more
  de: Mehr lesen
  cz: Čtěte dále
overview:
  en: All posts
  de: Alle Artikel
  cz: Všechny příspěvky
contact:
  en: Contact us!
  de: Schreib uns!
  cz: Napište nám!

t:
  en:
    info: "Information"
    address: "Address"
    phone: "Phone"
    ICO: "DIČ"
    ICO_id: "(Identification number)"

    latest-posts:  "Latest Posts"
    read-more:  "Read More →"
    show-more:  "Show More →"
    loading:  "Loading..."
    on-word: "on"
    contact: "Contact"
    contact-page: "contact.md"
    read-time: "min"
    comments: "comments"
    go-to-home-page: "Go to the Home Page"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"
    all-posts-category: "All posts in the category"
    privacy: "Privacy"
    privacy_url: "/privacy"

  de:
      info: "Informationen"
      address: "Adresse"
      phone: "Tel."
      ICO: "DIČ"
      ICO_id: "(Wirtschafts-Identifikationsnummer)"

      latest-posts:  "Neuste Artikel"
      read-more:  "Weiterlesen →"
      show-more:  "Mehr →"
      loading:  "Lädt..."
      on-word: "on"
      contact: "Kontakt"
      contact-page: "contact.md"
      read-time: "min"
      comments: "comments"
      go-to-home-page: "Zurück zur Startseite"
      months:
        january: "Jan"
        february: "Feb"
        march: "Mär"
        april: "Apr"
        may: "Mai"
        june: "Jun"
        july: "Jul"
        august: "Aug"
        september: "Sep"
        october: "Okt"
        november: "Nov"
        december : "Dez"
      all-posts-category: "Alle Artikel der Kategorie"
      privacy: "Datenschutz"
      privacy_url: "/datenschutz"

  cz:
      info: "Informace"
      address: "Adresa"
      phone: "Tel."
      ICO: "DIČ"
      ICO_id: ""

      latest-posts:  "Poslední přispěvek"
      read-more:  "Read More →"
      show-more:  "Show More →"
      loading:  "Načítaní..."
      on-word: "on"
      contact: "Kontakt"
      contact-page: "kontakt.md"
      read-time: "min"
      comments: "komentáře"
      go-to-home-page: "Zpět na hlavní stranu"
      months:
        january: "Led"
        february: "Únor"
        march: "Břez"
        april: "Dub"
        may: "Květ"
        june: "Červen"
        july: "Červenec"
        august: "Spr"
        september: "Září"
        october: "Říj"
        november: "List"
        december : "Pros"
      all-posts-category: "Všechny články v kategorii"
      privacy: "Práva"
      privacy_url: "/prava"

